### ISSUE TITLE
Horizontal page scroll.

### ISSUE THREAD

**Issue by UnnikrishnanSR-Accedo** [blipinsk/FlippableStackView#1]
Can you please suggest me the necessary changes  for implementing horizontal page scroll?

**Comment by blipinsk** [comment]
Basically you would have to modify `StackPageTransformer` to work horizontally and not vertically.
I will try to investigate it this evening if I could maybe implement this functionality into the library.

**Comment by UnnikrishnanSR-Accedo** [comment]
Thanks for the reply really appreciate...

**Comment by blipinsk** [comment]
The first version (still WIP) has been pushed to the repo. I think it does what you need... So if you dont need it to be anchored at left part of the screen, and you need it right now, feel free to use the code from `/feature/stack_anchoring` branch. I will try to implement it completely for `release/1.2.0` (currently I'm a bit short on time).

**Comment by UnnikrishnanSR-Accedo** [comment]
Hi Bartosz...The latest code is working perfect. Thanks for your hardwork and help :)

**Comment by blipinsk** [comment]
Awesome! :+1:  Glad I could help, feel free to star or start watching the project to show your support and to be up to date with any new upcoming features :)

**Comment by blipinsk** [comment]
The feature you were requesting has been implemented as a part of release 1.2.1. I decided to change the approach from anchoring the stack to LEFT, RIGHT, TOP or BOTTOM to setting an orientation of the stack (simply VERTICAL or HORIZONTAL).
