### ISSUE TITLE
Not able to get child view inside StackPageTransform

### ISSUE THREAD

**Issue by SumiGhosh** [blipinsk/FlippableStackView#10]
I was trying to get a child view from my ViewPager, but it returning error saying "cannot find symbol variable layout_divider".

**Comment by blipinsk** [comment]
Hi, 
this doesn't seem to be related to my library. `FlippableStackView` only changes the way your `ViewPager` is displaying elements. First of all I don't see a case in which I would like to get a child `View` inside a StackPageTransformer, second of all there is no `layout_divider` in my library. Look for an error in your adapter, or somewhere else in your code.
Cheers

**Comment by SumiGhosh** [comment]
Hi Bartosz Lipinski,

The scenario is when we have normal viewpager, we can take reference of the
child view using findviewbyid. In my case i used your classes in my project
and changed the animation of the view to look like a carousel, and when i
was trying to do the above said referencing to the childviews, i am getting
the error which i was saying.

I am not sure this is specific to the lib or not.

Thanks
Sumi Ghosh

**Comment by SumiGhosh** [comment]
Yeah, found a solution through ViewGroup.
