### ISSUE TITLE
Infinite View Pager And Swiping Effect

### ISSUE THREAD

**Issue by naveenvenkannagari** [blipinsk/FlippableStackView#13]
Hi I am using these library, couple of additional enhancements i need here
1) with Orientation Vertical i need horizontal swiping effect how to achieve these

2) Suppose i has 4 items in Flippable stack view after swiping the 4 item again if i swipe i should able to go to first item again its a kind of infinite view pager

Please tell me how can i achieve these two enhancements

**Comment by daentech** [comment]
I haven't tried to get the infinite swiping effect, but I have recently tried to get the vertical cards with horizontal scrolling.

Check out my fork to see:
https://github.com/daentech/FlippableStackView

I have updated the PageTransformer and the ViewPager (but this makes the library less flexible) and I have a known bug with scroll views inside the cards (I might have a solution to that, but I haven't tested it) but it should help you get started.

You should use Orientation.HORIZONTAL and you should see the cards stacked vertically, but swipeable horizontally.

**Comment by blipinsk** [comment]
Hi!
1) What do you mean exactly by "horizontal swiping effect", do you mean a tinder-like swiping effect?
2) `FlippableStackView` is just like a regular `ViewPager`, so if you wanna achieve an infinite stack you should look for a solution that lets you create an infinite `ViewPager` and adapt it for the `FlippableStackView`. You should look into [this](http://stackoverflow.com/questions/7766630/changing-viewpager-to-enable-infinite-page-scrolling) thread on StackOverflow. And I would especially check [this](http://stackoverflow.com/a/17424525/1993204) answer.
