### ISSUE TITLE
OnClicListener() && OnLongClicListener() doesn't work?

### ISSUE THREAD

**Issue by mscdroidlabs** [blipinsk/FlippableStackView#14]
Hi!

i have some problems to listen to this events, i tried to set clickable propertie in xml, also tried programattically "setClickacle(true)" but anything occurs. I only get working with OnTouchListener and then i have to play with ACTION_DOWN, ACTION_UP and ACTION_MOVE. 

Anyone has tried?

**Comment by blipinsk** [comment]
Hi @mscdroidlabs 
can you check if the same issue occurs if you use a regular `ViewPager` instead of `FlippableStackView`?

**Comment by mscdroidlabs** [comment]
You want i try separately in other activity/fragment or i change any class of flippablestack?

**Comment by blipinsk** [comment]
You need to swap the one you're having problem with. What are you setting this `OnClickListener` on? On `FlippableStackView` object?

**Comment by mscdroidlabs** [comment]
> `mPageAdapter = new ColorFragmentAdapter(getSupportFragmentManager(), mViewPagerFragments);
>                             mFlippableStack = (FlippableStackView) findViewById(R.id.flippable_stack_view);
>                             mFlippableStack.initStack(6, StackPageTransformer.Orientation.HORIZONTAL);
>                             mFlippableStack.setAdapter(mPageAdapter);
>                             mFlippableStack.setClickable(true);
> //Its hidden by default on my app
>                             mFlippableStack.setVisibility(View.VISIBLE);

```
                        mFlippableStack.setOnClickListener(new View.OnClickListener() {
                            @Override
                            public void onClick(View view) {
                                Toast.makeText(getApplicationContext(), "mFlippableStack ClicListener! ", Toast.LENGTH_SHORT).show();
                            }
                        });

                        mFlippableStack.setOnDragListener(new View.OnDragListener() {
                            @Override
                            public boolean onDrag(View view, DragEvent dragEvent) {
                                Log.d("TT", "Drag : " + dragEvent.toString() );
                                return false;
                            }
                        });`
```

The content of fragments is displayed whithout problems but, no one of this events is executed... :S

**Comment by blipinsk** [comment]
Ok so you're trying to set an `OnClickListener` on a `FlippableStackView` itself.
`OnClickListener` will not work for the `FlippableStackView` in the same way it will not work for the regular `ViewPager`. You can read the whole StackOverflow topic over [here](http://stackoverflow.com/questions/10243690/onclick-on-viewpager-not-triggered).

You should consider two things:
1. Think if you really want to implement an `OnClickListener` on the `FlippableStackView`... Maybe it's the contents of the `Stack` that should be implementing this functionality?
2. If you decide that it's really the `FlippableStackView` that needs that, try [this approach](http://stackoverflow.com/a/11666743/1993204).

**Comment by mscdroidlabs** [comment]
Nice! Big thanks!
