### ISSUE TITLE
Flip stacks at the run-time

### ISSUE THREAD

**Issue by NullPonyPointer** [blipinsk/FlippableStackView#15]
How can we flip stacks at the run-time, for example `setCurrentItem(...)` should behave but it's not working!

Any ideas?

**Comment by blipinsk** [comment]
`FlippableStackView` is just a `ViewPager` that displays its items a bit differently. You need to think of a way you would do this with a regular `ViewPager`.
You should use `setCurrentItem(...)` method.

**Comment by NullPonyPointer** [comment]
Thanks for your fast response, as I already mentioned I have used the following method:

`stack.setCurrentItem(stack.getCurrentItem() + 1, true);` 
or 
`stack.setCurrentItem(stack.getCurrentItem() - 1, true);`

But nothing happens!

**Comment by blipinsk** [comment]
I'm trying the same thing with the sample app and it's working correctly. Is your issue with the fact that you cannot see the actual _flip_?
