### ISSUE TITLE
Init with gravity does not react on Lolipop 5.0.1

### ISSUE THREAD

**Issue by CodeCombiner** [blipinsk/FlippableStackView#19]
Hi, I want to place fragments of stack in direction from top to bottom, just in oppopsite as in example on the main page https://github.com/blipinsk/FlippableStackView/blob/master/FlippableStackView.gif
I call init like so
`
mFlippableStack.initStack(2, StackPageTransformer.Orientation.VERTICAL, 0.9f, 0.5f, 1f, StackPageTransformer.Gravity.BOTTOM);
`
Also I change to StackPageTransformer.Gravity.TOP   but it seems the 'init' does not react to this parameter.
May I receive some suggestion please

**Comment by blipinsk** [comment]
Hi,
the `Gravity` parameter causes a different effect that you think it does. If the height of the `ViewPager's` is bigger than the `stack's` height, then the gravity parameter is applied, and the stack is properly moved horizontally. It's not affecting the anchoring of the stack.
