### ISSUE TITLE
How to show items in a loop?

### ISSUE THREAD

**Issue by a-klimashevsky** [blipinsk/FlippableStackView#2]
In a default implementation i cannot scroll out of bounds.
How can I scroll items in a loop?
For example:
I have items 1,2,3,4. Now app shows item 4. I cannot scroll bottom (to item 1). How I can do it?
In a OrientedViewPager there are checks for the first and the last items.

Thanks.

**Comment by blipinsk** [comment]
`OrientedViewPager` is just a regular `ViewPager` (management and operation wise). The only difference is that it lets you choose its orientation (`VERTICAL` or `HORIZONTAL`).

The whole library (`FlippableStackView`) is based on this `ViewPager`. There is no method in original `ViewPager` to make it loop through its children, therefore there is no default way to do that in `FlippableStackView`. To do that you have to implement looping yourself, just like you would for any `ViewPager`.
