### ISSUE TITLE
Crashed on android 6.0

### ISSUE THREAD

**Issue by sleith** [blipinsk/FlippableStackView#20]
Hi sir,
Somehow i got crashed when testing on simulator 6.0. It works fine on my phone 4.x
The crash log:

03-14 13:48:09.027 12923-12965/myapp W/EGL_emulation: eglSurfaceAttrib not implemented
03-14 13:48:09.027 12923-12965/myapp W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0x9ee09a20, error=EGL_SUCCESS
03-14 13:48:09.111 12923-12965/myapp E/Surface: getSlotFromBufferLocked: unknown buffer: 0x9f2a0eb0
03-14 13:48:10.947 12923-12987/myapp A/OpenGLRenderer: Error: Spot pair overflow!!! used 29, total 18
03-14 13:48:10.947 12923-12987/myapp A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 12987 (hwuiTask1)

Any idea why?
Thanks :)

**Comment by blipinsk** [comment]
Hi,
I'm using this library with Android 6.0 with no problems what so ever. So this issue is not Marshmallow-related. There must be something else wrong. Can't really tell from the log you've provided though... sorry :cry:

**Comment by manavpatadia** [comment]
I have faced the same error.
