### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by edbond** [blipinsk/FlippableStackView#21]
Thanks for the great library.

I have two questions:
- how to implement infinite loop to allow to swipe indefinitely?
- how to make horizontal swipes in both direction - left or right? Both loads next card.

Thanks!

**Comment by blipinsk** [comment]
Hi, thanks for the issue.
As for the infinite loop check my answer [here](https://github.com/blipinsk/FlippableStackView/issues/2).
The latter thing is much more complicated and has been very briefly discussed [here](https://github.com/blipinsk/FlippableStackView/issues/3).
