### ISSUE TITLE
Stack Position changing

### ISSUE THREAD

**Issue by renjithkrish89** [blipinsk/FlippableStackView#23]
Hi, Thanks for the great Library. I need a help in the stack of the library. Currently in Horizontal orientation of the library the stack are in left side of the view. My requirement is that i need that stack in the Top of the view like in the orientation Vertical. How can I achieve that.Please Help.

**Comment by blipinsk** [comment]
Hi,
the stack anchoring is not that trivial, some more information in the issue #3
