### ISSUE TITLE
StackAlways Aligned Center 

### ISSUE THREAD

**Issue by trinadhkoya** [blipinsk/FlippableStackView#28]
I just want to make it aligned to quite right of my Layout.But it always aligned to centered only.Even though i make some changes like layout:gravity:start and so on

**Comment by blipinsk** [comment]
I already answered that through email:
> FlippableStackView only supports „moving” the stack within the chosen orientation (i.e. top/center/bottom for vertical stack).

In other words you cannot use `gravity` to align it to right or left.

**Comment by trinadhkoya** [comment]
Okay ,i don't know what you are talking about.i am asking about position of the Layout i.e StackView .Suppose if we have a image ,we can align it to center or top or left or bottom.Can't we do the same for this StackView.i guess we can .

**Comment by blipinsk** [comment]
no.

**Comment by trinadhkoya** [comment]
how to eliminate the space around the StackView then?UI doesnot look good right ?

**Comment by blipinsk** [comment]
Why don't you read through the Readme first. Then if you have further questions, I can try to help you.

**Comment by trinadhkoya** [comment]
I have gone through it Sir,I couldn't find anything related to that Stuff.

**Comment by blipinsk** [comment]
Did you try the last stack initialization method?
