### ISSUE TITLE
How can i set selection at particular index.

### ISSUE THREAD

**Issue by ChetnaNakum** [blipinsk/FlippableStackView#29]
I am unable to set index .

**Comment by blipinsk** [comment]
Have you tried [`setCurrentItem(int item)`](https://github.com/blipinsk/FlippableStackView/blob/master/library/src/main/java/com/bartoszlipinski/flippablestackview/OrientedViewPager.java#L409) or [`setCurrentItem(int item, boolean smoothScroll)`](https://github.com/blipinsk/FlippableStackView/blob/master/library/src/main/java/com/bartoszlipinski/flippablestackview/OrientedViewPager.java#L420)?

**Comment by ChetnaNakum** [comment]
There is no such a method in CardStackView class.

**Comment by blipinsk** [comment]
`CardStackView` class is not the part of my library

**Comment by ChetnaNakum** [comment]
Oops! It's Typos.It is CardStack

**Comment by blipinsk** [comment]
Still not this library 😉

**Comment by ChetnaNakum** [comment]
ahhh! Sorry Wrong Window.
