### ISSUE TITLE
PageChangeListener not available?

### ISSUE THREAD

**Issue by brije111** [blipinsk/FlippableStackView#32]
How can I listen for the page(stack View) change listener as we get in normal view pager in android?

**Comment by blipinsk** [comment]
It has the (now deprecated) `setOnPageChangeListener`:
https://github.com/blipinsk/FlippableStackView/blob/04661f04a26776ea300de10a6ca8e0e84a88daab/library/src/main/java/com/bartoszlipinski/flippablestackview/OrientedViewPager.java#L520
