### ISSUE TITLE
StackView Position issue

### ISSUE THREAD

**Issue by technicaddc** [blipinsk/FlippableStackView#33]
I want to get stack position but "  return this.fragments.size();" this code not get true postion what can I do

**Comment by blipinsk** [comment]
@technicaddc did you try `getCurrentItem` method?

https://github.com/blipinsk/FlippableStackView/blob/2ad24bb9ae7a2c801193fc61811ddf0d30269d66/library/src/main/java/com/bartoszlipinski/flippablestackview/OrientedViewPager.java#L425

**Comment by technicaddc** [comment]
Thanks its working :)
