### ISSUE TITLE
Any function to disable swipe?

### ISSUE THREAD

**Issue by Kenwaves-Dev** [blipinsk/FlippableStackView#35]
Is there any function or method to disable swiping of stacks?

**Comment by blipinsk** [comment]
@Kenwaves-Dev not OOTB, you will need to subclass `FlippableStackView`, just like in [this example someone does for a regular `ViewPager`](https://stackoverflow.com/a/13437997/1993204)

**Comment by Kenwaves-Dev** [comment]
Thank you
