### ISSUE TITLE
How to increase the overlap height above 1.0f  for the stackview ???

### ISSUE THREAD

**Issue by sohanshetty** [blipinsk/FlippableStackView#5]

**Comment by blipinsk** [comment]
Duplicate of: https://github.com/blipinsk/FlippableStackView/issues/4

Please stop duplicating issues. I assure you, you won't receive the answer earlier if you keep duplicating issues.

**Comment by sohanshetty** [comment]
Oh sorry desperately needed solution :( please help me out

**Comment by sohanshetty** [comment]
HI blipinsk

Is it possible atleast because i'm already out of deadline now

Thank you
