### ISSUE TITLE
Card aligned on left

### ISSUE THREAD

**Issue by thepelican** [blipinsk/FlippableStackView#6]
Hi All,

I m having an issue when i relaod the stack: basically when Im reloading the stack, and it doesnt respect my layout. I get that only card aligned on the left. Then if put more elements on the stack and i relaod it everything seems to be fine and all my cards are aligned as expected. 

I really cant fix this misalignment, can anyone help me with this?

**Comment by blipinsk** [comment]
Can you provide some details of your issue? Like what sort of layout it (stack) doesn't respect. Maybe some screens?

**Comment by sohanshetty** [comment]
Hi
#6 issue can be solved by setting the flippablestackView  to setCurrentItem(yourNewPosition, true). This make the fragment to scroll smoothly and it wont aligned  the layout to left when it reloads.

ThankYou
Sohan
