### ISSUE TITLE
Crash on Lollipop

### ISSUE THREAD

**Issue by Prayer-RecycleSmart** [blipinsk/FlippableStackView#8]
Hey guys,

with android 6.0 (sdk 23) we have this issue every time we swipe on a card...

E/OpenGLRenderer﹕ resultIndex is -1, the polygon must be invalid!
A/libc﹕ Fatal signal 7 (SIGBUS), code 1, fault addr 0xaa in tid 13796 (hwuiTask1)

Any clue?

**Comment by blipinsk** [comment]
Hi,

are you sure it's due to the `FlippableStackView` itself and not due to the content of the adapter?
I don't really have the ability to try the library on a real device (with 6.0), but it does not crash for me on 6.0 emulator.

Cheers,
Bartek

**Comment by blipinsk** [comment]
I just ran the sample app on Nexus 5 6.0. No issues. I don't think the problem is library-related. Give me a heads up if you find the reason for your crash.

**Comment by nicholrgUW** [comment]
I'm having the same issue as Prayer-RecycleSmart on a Nexus 7 tablet running Android 6.0. When trying to swipe to a fragment that does not exist (i.e. at the front or back of the stack). This typically happens with a "forceful" swipe.
